In [1]:
import torch

# Tensors

- PyTorch is a library for processing tensors.
- A Tensor is a number, vector, matrix or any n-dimensional array.

In [2]:
#Number
t1 = torch.tensor(4.) #Decimal indicates float
t1

tensor(4.)

In [3]:
#DataType
t1.dtype

torch.float32

In [4]:
#Vector
t2 = torch.tensor([1., 2, 3, 4])
t2 #Outputs are all float because a tensor can hold only one type of data type.

tensor([1., 2., 3., 4.])

In [5]:
#Matrix
t3 = torch.tensor([[5., 6], 
                  [7,8], 
                  [9,10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [6]:
#3-Dimensional Array
t4 = torch.tensor([[[11, 12, 13], 
                    [13, 14, 15]],
                   [[15, 16, 17],
                    [17, 18, 19.]]])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [7]:
#Shape
t4.shape

torch.Size([2, 2, 3])

# Tensor Operations and Gradients
We can combine tensors with arithmetic operations.

In [21]:
#Create Tensors
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

In [22]:
#Arithmetic Operations
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

 - PyTorch can automatically compute the derivative of y w.r.t the tensors that have `requires_grad` set to `True`, i.e., w and b. 
 - The derivatives of `y` w.r.t the input tensors are stored in the `.grad` property of the respective tensors.

In [24]:
#Gradients

print('dy/dx = ', x.grad)
print('dy/dw = ', w.grad)
print('dy/db = ', b.grad) #.grad stands for gradient

dy/dx =  None
dy/dw =  None
dy/db =  None


# Interoperability with NumPy

In [25]:
import numpy as np

x = np.array([[1,2], [3,4.]])
x

array([[1., 2.],
       [3., 4.]])

Convert Numpy array to PyTorch Tensor using `torch.from_numpy`.

In [26]:
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [27]:
#DataTypes

x.dtype, y.dtype

(dtype('float64'), torch.float64)

To convert a tensor to numpy array use `.numpy` method.

In [28]:
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])